# Generated by Django 5.2.4 on 2025-07-27 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(help_text='13-digit ISBN', max_length=13, unique=True)),
                ('category', models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('science', 'Science'), ('technology', 'Technology'), ('history', 'History'), ('biography', 'Biography'), ('education', 'Education'), ('reference', 'Reference'), ('literature', 'Literature'), ('other', 'Other')], max_length=50)),
                ('total_copies', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_copies', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('shelf_location', models.CharField(help_text='e.g., A1-B2', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'books',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='OPACSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=500)),
                ('search_type', models.CharField(choices=[('title', 'Title'), ('author', 'Author'), ('isbn', 'ISBN'), ('category', 'Category'), ('general', 'General Search')], default='general', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('results_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'opac_search_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
