# Generated by Django 5.2.4 on 2025-07-27 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='librarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_borrows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='borrowrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['borrowed', 'overdue'])), fields=('user', 'book'), name='unique_active_borrow'),
        ),
    ]
